### ISSUE TITLE
只能下载多页相册的第一页

### ISSUE THREAD

**Issue by swing0828** [einverne/douban-dl#1]
豆瓣相册只能下载多页相册的第一页，这个怎么解决？第一次下载的时候可以下载所有页面，第二次下的时候所有的相册只能下载第一页的照片，其他页的显示已存在：<相片名称> exist skip

**Comment by swing0828** [comment]
查了下原因：豆瓣更新，用户相册分页参数由start更新为m_start，导致只能下载第一页。这个能修复吗？

**Comment by einverne** [comment]
我修一下
